# version: "3.7"

# services:
#   elasticsearch:
#     platform: linux/amd64
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
#     environment:
#       - node.name=elasticsearch
#       - discovery.type=single-node
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     ports:
#       - "9200:9200"
#     networks:
#       - elk
  
#   logstash:
#     platform: linux/amd64
#     image: docker.elastic.co/logstash/logstash:7.10.0
#     volumes:
#       - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#       - ../logs:/usr/share/logstash/logs
#     environment:
#       - LS_JAVA_OPTS=-Xms256m -Xmx256m
#     ports:
#       - "5044:5044"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

#   kibana:
#     platform: linux/amd64
#     image: docker.elastic.co/kibana/kibana:7.10.0
#     ports:
#       - "5601:5601"
#     networks:
#       - elk
#     depends_on:
#       - elasticsearch

#   filebeat:
#     platform: linux/amd64
#     image: docker.elastic.co/beats/filebeat:7.10.0
#     user: root
#     volumes:
#       - ../logs:/usr/share/filebeat/logs
#       - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#     depends_on:
#       - elasticsearch
#       - logstash
#     networks:
#       - elk

# volumes:
#   esdata:
#     driver: local

# networks:
#   elk:
#     driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    platform: linux/arm64
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    platform: linux/arm64
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    platform: linux/arm64
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    platform: linux/arm64
    user: root
    depends_on:
      - logstash
    networks:
      - elk

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
